### ISSUE TITLE
in v1.0.5， file not in PDF format or corrupted

### ISSUE THREAD

**Issue by junchenChow** [voghDev/PdfViewPager#101]
in v1.0.5
E/System: java.io.IOException: file not in PDF format or corrupted
at android.graphics.pdf.PdfRenderer.nativeClose(Native Method)
at android.graphics.pdf.PdfRenderer.doClose(PdfRenderer.java:250)
at android.graphics.pdf.PdfRenderer.finalize(PdfRenderer.java:238)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
at java.lang.Daemons$Daemon.run(Daemons.java:105)
at java.lang.Thread.run(Thread.java:764)

url:
http://huyi-oss-user.oss-cn-shanghai.aliyuncs.com/1_1026443901453451265_1034325014347726849_contract_1535437315336_imgoss1

Once this problem occurs, the PDF after normal loading can not be opened.

**Comment by voghDev** [comment]
This photo of the cat is awesome, but you mean

Are you trying to load this URL in a PdfViewPager? this is a `jpeg` image, the error in file format makes sense.

Can you try to load this URL in your remote PDF viewer? 

http://css4.pub/2015/textbook/somatosensory.pdf

**Comment by junchenChow** [comment]
1

**Comment by dikadk** [comment]
Seems like issue is coming from PdfRenderer itself. There is an open issue on Google Samples repo https://github.com/googlesamples/android-PdfRendererBasic/issues/25

**Comment by jazarja** [comment]
I have same problem, some PDF files cannot be rendered with PdfRenderer (sample: http://www.idx.co.id/StaticData/NewsAndAnnouncement/ANNOUNCEMENTSTOCK/From_EREP/201904/4bbbfa5fef_e29a7a2112.pdf). 

> java.io.IOException: file not in PDF format or corrupted
    at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
    at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:167)
    at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:75)
    at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:57)
    at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:39)
    at xxxx.PdfViewer.onSuccess(PdfViewer.java:62)
    at es.voghdev.pdfviewpager.library.RemotePDFViewPager.onSuccess(RemotePDFViewPager.java:88)
    at es.voghdev.pdfviewpager.library.remote.DownloadFileUrlConnectionImpl$2.run(DownloadFileUrlConnectionImpl.java:95)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by voghDev** [comment]
Closing this due to inactivity
