### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Br1125** [voghDev/PdfViewPager#111]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getCacheDir()' on a null object reference
                      at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.getSeekableFileDescriptor(BasePDFPagerAdapter.java:110)
                      at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:75)
                      at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:57)
                      at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:44)
                      at com.whiteboard.teacher.fragment.YunFragment.onSuccess(YunFragment.java:1385)
                      at es.voghdev.pdfviewpager.library.RemotePDFViewPager.onSuccess(RemotePDFViewPager.java:70)
                      at es.voghdev.pdfviewpager.library.remote.DownloadFileUrlConnectionImpl$2.run(DownloadFileUrlConnectionImpl.java:96)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6812)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by voghDev** [comment]
Hi

If you read the error, you will see that you are calling `getCacheDir()` on a null object. Probably your context is null due to a de-attached fragment or destroyed Activity. Also check that you have read permissions on the SD card before doing operations with the file system.

Thanks for using the lib

**Comment by voghDev** [comment]
Closing this due to inactivity
