### ISSUE TITLE
在加载的过程中按返回键直接退出程序

### ISSUE THREAD

**Issue by xiaozou00123** [voghDev/PdfViewPager#119]
你好，在加载PDF的时候，按返回键，直接退出了软件

**Comment by xiaozou00123** [comment]
正常的思路应该是 取消加载pdf

**Comment by voghDev** [comment]
Hi,

could you translate the issue please?

**Comment by xiaozou00123** [comment]
hi,
When loading the PDF, Press the return key, it not Unload PDF but exit App

**Comment by xiaozou00123** [comment]
03-26 22:36:44.823 23789-23789/com.example.administrator.youke E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.example.administrator.youke, PID: 23789
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getCacheDir()' on a null object reference
                                                                                     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.getSeekableFileDescriptor(BasePDFPagerAdapter.java:110)
                                                                                     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:75)
                                                                                     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:57)
                                                                                     at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:39)
                                                                                     at com.example.administrator.youke.VedioContentDetail.HomeWorkFragment.onSuccess(HomeWorkFragment.java:201)
                                                                                     at es.voghdev.pdfviewpager.library.RemotePDFViewPager.onSuccess(RemotePDFViewPager.java:88)
                                                                                     at es.voghdev.pdfviewpager.library.remote.DownloadFileUrlConnectionImpl$2.run(DownloadFileUrlConnectionImpl.java:95)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5554)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

**Comment by voghDev** [comment]
As the error says, your App's cache directory is not readable or writable. This issue is probably related to permissions. The PDF File is loaded in your SD card, so you probably need to request `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` permissions before loading the PDF file. This code might work in an Activity or Fragment:

    requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, WRITE_PERMISSIONS_REQUEST_CODE);
