### ISSUE TITLE
 pointerIndex out of range

### ISSUE THREAD

**Issue by shinelyme** [voghDev/PdfViewPager#133]
1.0.5上手指滑动会报这个错误，麻烦博主看下

Java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2201)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2522)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2680)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:452)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3361)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:414)
        at android.view.View.dispatchPointerEvent(View.java:12066)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5048)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4855)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4385)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4438)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4404)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4531)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4412)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4588)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4385)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4438)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4404)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4412)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4385)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7020)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6992)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6949)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7143)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:257)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:331)
        at android.os.Looper.loop(Looper.java:149)
        at android.app.ActivityThread.main(ActivityThread.java:6662)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by voghDev** [comment]
Hello!

This is a classic issue :) You can have a look at #43, #123, #100, #83, #20, #19 or #14 to see the solution

Thanks!
