### ISSUE TITLE
Android.graphics.pdf.PdfRenderer.finalize() timed out after 10 

### ISSUE THREAD

**Issue by dembal1990** [voghDev/PdfViewPager#17]
I have already implemented open pdf file from SD card, but sometimes it crashes.
EXCEPTION:

```
08-10 15:11:03.952 1617-1635/com.notviz.android E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
Process: com.notviz.android, PID: 1617
java.util.concurrent.TimeoutException: android.graphics.pdf.PdfRenderer.finalize() timed out after 10 seconds
at android.graphics.pdf.PdfRenderer.nativeClose(Native Method)
at android.graphics.pdf.PdfRenderer.doClose(PdfRenderer.java:223)
at android.graphics.pdf.PdfRenderer.finalize(PdfRenderer.java:212)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
at java.lang.Thread.run(Thread.java:818)
08-10 15:11:13.739 1617-1638/com.notviz.android D/ANRAppManager: !!! It is not under singleton mode, U can't use it. !!!
08-10 15:11:13.740 1617-1638/com.notviz.android W/Binder: Caught a RuntimeException from the binder stub implementation.
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.mediatek.anrappmanager.IFrameworks.serviceManagerGetService(java.lang.String)' on a null object reference
at com.mediatek.anrappmanager.ANRManagerNative$1.b(SourceFile:77)
at com.mediatek.anrappmanager.ANRManagerNative$1.c(SourceFile:75)
at ...
```

**Comment by voghDev** [comment]
Hi,

when does this happen? when opening the PDF file? or when closing the app?

Looks like a PdfRenderer issue. I'll have a look.

**Comment by AlienAsRoger** [comment]
I have problem for this as well:

Devices are : Samsung SM-T805 	5.0.2, SM-T805 5.0.2, LG-D855 5.0
```
Fatal Exception: java.util.concurrent.TimeoutException: android.graphics.pdf.PdfRenderer.finalize() timed out after 10 seconds
       at android.graphics.pdf.PdfRenderer.nativeClose(PdfRenderer.java)
       at android.graphics.pdf.PdfRenderer.doClose(PdfRenderer.java:219)
       at android.graphics.pdf.PdfRenderer.finalize(PdfRenderer.java:208)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:209)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:192)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by voghDev** [comment]
Hi again,

could you send a link to a PDF where this error appears? 
I'd never seen it, so I'd like to test it in my devices and see what's happening.

**Comment by shineon84** [comment]
Hi voghDev, I have the same problem too!

**Comment by voghDev** [comment]
Hello,
In search for deeper information about this issue, [this answer](https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin) is very helpful. The error is related to GC while Android turns the phone into a "Low battery consumption" mode. A proposed solution to mitigate the error is to acquire a WAKE_LOCK while the user is reading the PDF document. I haven't tried that yet.

Good to have a PDF that causes the crash. We will try to reproduce your case and post any news.
