### ISSUE TITLE
Crash on Android 10

### ISSUE THREAD

**Issue by shahzad1** [voghDev/PdfViewPager#178]
Caused by: android.view.InflateException: Binary XML file line #13 in com.example.packagename:layout/view_pdf_page: Error inflating class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
    Caused by: java.lang.ClassNotFoundException: com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1140)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1101)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.instantiateItem(PDFPagerAdapter.java:45)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:24726)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24726)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6931)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:24726)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6931)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:490)
        at android.view.View.measure(View.java:24726)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6931)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24726)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6931)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24726)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6931)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:746)
        at android.view.View.measure(View.java:24726)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3165)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1933)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2233)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1821)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7916)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:980)
        at android.view.Choreographer.doCallbacks(Choreographer.java:804)
        at android.view.Choreographer.doFrame(Choreographer.java:739)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
2020-12-30 16:40:09.393 19428-19428/com.example.packagename E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView" on path: DexPathList[[zip file "/data/app/com.example.packagename-sjPibPrztVo-cxv9DVBZCA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.packagename-sjPibPrztVo-cxv9DVBZCA==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 53 more

**Comment by voghDev** [comment]
Hi! 

can you provide more details about the issue? please attach the issue template filled completely :-)
