### ISSUE TITLE
Crash - es.voghdev.pdfviewpager.library.util.VerticalViewPager.onInterceptTouchEvent

### ISSUE THREAD

**Issue by abhinavtestbook** [voghDev/PdfViewPager#179]
Receiving this crash oftentimes in my crashlytics . Not android version/device specific , have came in almost all versions.

`Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getY(MotionEvent.java:2382)
       at androidx.core.view.MotionEventCompat.getY(MotionEventCompat.java:521)
       at es.voghdev.pdfviewpager.library.util.VerticalViewPager.onInterceptTouchEvent(VerticalViewPager.java:1619)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2635)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:489)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4078)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:447)
       at android.view.View.dispatchPointerEvent(View.java:14264)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5828)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5614)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5115)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5168)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5134)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5274)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5142)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5331)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5115)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5168)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5134)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5142)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5115)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7897)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7866)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7809)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8027)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:213)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7973)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8051)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1043)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:793)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1028)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7574)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by voghDev** [comment]
Classic issue :slightly_smiling_face: some duplicates are #19 #20 #21 #71 #43 #83 #100 #103 #123 #133 You can have a look at the solutions there
