### ISSUE TITLE
Crash when opening password protected pdf

### ISSUE THREAD

**Issue by slowcar** [voghDev/PdfViewPager#185]
As the library wraps opening a pdf, it should handle an encrypted or password protected pdf gracefully.

java.lang.SecurityException: password required or incorrect password
        at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
        at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:166)
        at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:89)
        at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:71)
        at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:43)
        at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter$Builder.create(PDFPagerAdapter.java:149)
        at es.voghdev.pdfviewpager.library.PDFViewPager.initAdapter(PDFViewPager.java:70)
        at es.voghdev.pdfviewpager.library.PDFViewPager.init(PDFViewPager.java:43)
        at es.voghdev.pdfviewpager.library.PDFViewPager.<init>(PDFViewPager.java:33)

**Comment by voghDev** [comment]
Hi! Thanks for reporting.

Yes, it is not the first time users try to open a password protected Pdf. If you have some sample code that opens the protected file successfully, I'll have a look and think about adding this feature: Supporting opening password protected files
