### ISSUE TITLE
Error when try "Zoom out" and "Zoom in" very Quick

### ISSUE THREAD

**Issue by irsalshabirin** [voghDev/PdfViewPager#20]
```
Process: com.jatim, PID: 23510
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:2031)
at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:116)
at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:496)
at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2058)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1961)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
at android.app.Activity.dispatchTouchEvent(Activity.java:2801)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
at android.view.View.dispatchPointerEvent(View.java:8686)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4168)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4034)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3584)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3637)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3603)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3720)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3611)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3777)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3584)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3637)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3603)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3611)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3584)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5852)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5826)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5797)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5942)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5298)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
```

in API 22, Marshmellow, please help me, thanks 👍  👍  👍

**Comment by voghDev** [comment]
Hi,
thanks for using the lib

You are probably experiencing the same issue as #14. Please try one of the solutions exposed there and let me know if it works for you

**Comment by irsalshabirin** [comment]
yes, it works, thanks. 👍  👍  👍
