### ISSUE TITLE
Crash on a lot of mobile phones

### ISSUE THREAD

**Issue by pengfeigao** [voghDev/PdfViewPager#26]
Crash log：
`java.lang.NoClassDefFoundError: android.graphics.pdf.PdfRenderer
	at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:75)
	at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:57)
	at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:44)
	at com.jrj.tougu.td.activity.ResearchesDetailActivity.onSuccess(ResearchesDetailActivity.java:70)
	at es.voghdev.pdfviewpager.library.RemotePDFViewPager.onSuccess(RemotePDFViewPager.java:66)
	at es.voghdev.pdfviewpager.library.remote.DownloadFileUrlConnectionImpl$2.run(DownloadFileUrlConnectionImpl.java:95)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5315)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)`

![qq 20161116103058](https://cloud.githubusercontent.com/assets/9261499/20332593/df35c7d4-abe7-11e6-918d-cddc0a4be244.png)

all console log file：
[issue.txt](https://github.com/voghDev/PdfViewPager/files/593654/issue.txt)

**Comment by voghDev** [comment]
Hi,

thanks for using the lib

`java.lang.NoClassDefFoundError: android.graphics.pdf.PdfRenderer` means that all these devices have Android versions below Lollipop (5.0 - API 21).

Before rendering the PDF, you need to check if device has Lollipop or not, and use the legacy implementation if below. Sample code could be the following:

    boolean isLollipopOrHigher = Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP;
    if(isLollipopOrHigher) {
        // Use PdfViewPager
    } else {
        // Use legacy implementation
    }

Refer to #9 for implementing legacy version

Let me know any further issues

**Comment by pengfeigao** [comment]
Why must be used in more than the Lollipop (5.0 - API 21)?

**Comment by pengfeigao** [comment]
Thinks!

**Comment by voghDev** [comment]
No, the library does not think! But I try to... ;)

you're welcome!
