### ISSUE TITLE
App crashes with OutOfMemory issue

### ISSUE THREAD

**Issue by snchitnis** [voghDev/PdfViewPager#35]
I have a pdf with 2 MB size. I am downloading the file from server first time and then storing it in Application Memory with MODE_PRIVATE. I can open and read the file easily with normal flow. 

But, when I play to and fro with this fragment quickly I get crash with following exception. 

 java.lang.OutOfMemoryError: Failed to allocate a 7755276 byte allocation with 4194208 free bytes and 5MB until OOM
                                                                                    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                    at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
                                                                                    at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
                                                                                    at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.createBitmapAtIndex(SimpleBitmapPool.java:83)
                                                                                    at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.getBitmap(SimpleBitmapPool.java:49)
                                                                                    at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.get(SimpleBitmapPool.java:59)
                                                                                    at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.instantiateItem(PDFPagerAdapter.java:59)
                                                                                    at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1248)
                                                                                    at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                    at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:540)

I guess there are multiple threads opened to load file in memory and due to which app goes to OutOfMemory. How can I clear memory when I move away from PDF Viewer Fragment?

**Comment by voghDev** [comment]
Have you called `close()` on each fragment's onDestroy?

**Comment by snchitnis** [comment]
Yes, I have called adapter.close() in onDestroy

**Comment by voghDev** [comment]
I see,

what I would do is to try a lighter PDF, though 2 mb shouldn't be a problematic size. Can you try the lightest one on the examples?

**Comment by snchitnis** [comment]
Yes, I tried with 500 Kb PDF and  it works smoothly. So I tried to increase application heap size, but still it crashes for that 2 MB file

**Comment by voghDev** [comment]
Aha,

and are you opening a single PdfViewPager? or various instances at the same time? Another interesting test I would do is declaring an empty Activity with only one PdfViewPager. Make it your app entry point in your manifest, and see if you still have OOM

**Comment by snchitnis** [comment]
Issue Solved. 
Actually, I was using "BasePDFPagerAdapter" instead of "PDFPagerAdapter", made changes accordingly and issue resolved. 

Thanks for your help :)

**Comment by voghDev** [comment]
You're welcome :)
