### ISSUE TITLE
onSuccess Error

### ISSUE THREAD

**Issue by ahmtkocamn** [voghDev/PdfViewPager#4]
java.lang.NoClassDefFoundError: android.graphics.pdf.PdfRenderer
help.

**Comment by voghDev** [comment]
Sounds like you are running on a device below API 21. Is your phone/emulator running Android Lollipop or higher?

If not, you'll have to call the system native intent to display PDF documents. See the [Legacy sample](https://github.com/voghDev/PdfViewPager/blob/master/sample/src/main/java/es/voghdev/pdfviewpager/LegacyPDFActivity.java)

**Comment by KhushbooTahir** [comment]
**java class:**
public class RemotePDF extends AppCompatActivity implements DownloadFile.Listener {
    RemotePDFViewPager remotePDFViewPager;
    PDFPagerAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

       remotePDFViewPager =
                new RemotePDFViewPager(getApplicationContext(), "http://partners.adobe.com/public/developer/en/xml/AdobeXMLFormsSamples.pdf", this);



    }

    @Override
     public void onSuccess(String url, String destinationPath) {
        adapter = new PDFPagerAdapter(this, "AdobeXMLFormsSamples.pdf");
        remotePDFViewPager.setAdapter(adapter);
        setContentView(remotePDFViewPager);
    }

    @Override
    public void onFailure(Exception e) {
        // This will be called if download fails
    }

    @Override
    public void onProgressUpdate(int progress, int total) {
        // You will get download progress here
        // Always on UI Thread so feel free to update your views here
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        adapter.close();
    }


}

Xml:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.example.pdfviewer.MainActivity">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Welcome to View PDF file"/>

    <es.voghdev.pdfviewpager.library.PDFViewPager
        android:id="@+id/pdfViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
       />
</RelativeLayout>

running  device Android Version 4.1.2 .   But I am still getting error on Success . Kindly help 

**Error:**


E/dalvikvm: Could not find class 'android.graphics.pdf.PdfRenderer', referenced from method es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init
11-15 15:36:38.757 27359-27359/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NoClassDefFoundError: android.graphics.pdf.PdfRenderer
                                                       at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:75)
                                                       at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:57)
                                                       at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:44)
                                                       at com.example.pdfviewer.RemotePDF.onSuccess(RemotePDF.java:33)
                                                       at es.voghdev.pdfviewpager.library.RemotePDFViewPager.onSuccess(RemotePDFViewPager.java:66)
                                                       at es.voghdev.pdfviewpager.library.remote.DownloadFileUrlConnectionImpl$2.run(DownloadFileUrlConnectionImpl.java:95)
                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by voghDev** [comment]
Exactly. Your device is Api Level 16 (see [Android API levels](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html)) and PdfRenderer class requires API level 21 (5.0) or above

You can implement the [legacy sample](https://github.com/voghDev/PdfViewPager/blob/master/sample/src/main/java/es/voghdev/pdfviewpager/LegacyPDFActivity.java) for your ICS or Jelly Bean device
