### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by pengfeigao** [voghDev/PdfViewPager#43]
`java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2014)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1961)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1722)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2786)
	at com.jinxuanjin.jxgold.tougu.activity.BaseActivity.dispatchTouchEvent(BaseActivity.java:627)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
	at android.view.View.dispatchPointerEvent(View.java:8753)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4002)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3750)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5820)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5794)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5765)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5910)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5881)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5933)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
`

**Comment by pengfeigao** [comment]
The investigation found that this was a ViewPager of Android's bug, which occasionally happens when the user performs multitouch operations. The problem persists until at least Android 4.4.
The solution is simple, overwriting the ViewPager's onTouchEvent and onInterceptTouchEvent methods, and the catch exception, as follows:
`
3
4
5
6
7
8
9
@Override
    public boolean onTouchEvent(MotionEvent me) {
        try {
            return super.onTouchEvent(me);
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return false;
    }`

**Comment by voghDev** [comment]
Hello,

I remember issues when zooming and panning related to onTouchEvent. Are you using the last version of the library? (`1.0.1` or `1.0.2`). Several issues were fixed in the `PdfViewPager` class.

If yours is an additional one that isn't fixed yet, I'll try to add the solution

Thanks for your feedback

**Comment by KomoriWu** [comment]
My version1.0.2 . 
I also met.
Thank you 1L

**Comment by voghDev** [comment]
According to @pengfeigao's comment, this issue is similar to #14. You can find the solution in his comment or in the linked issue. Thanks for the feedback & for using the lib guys :-)
