### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by MadAxon** [voghDev/PdfViewPager#62]
PdfViewPager worked without any problem but today it got crashed. The app crashes at this line: `remotePDFViewPager = new RemotePDFViewPager(this, pdfUrl, this);`

Stacktrace:
`java.lang.IllegalStateException: Cannot access request header fields after connection is set
                                                                          at com.android.okhttp.internal.http.HttpURLConnectionImpl.getRequestProperties(HttpURLConnectionImpl.java:188)
                                                                          at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getRequestProperties(DelegatingHttpsURLConnection.java:182)
                                                                          at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getRequestProperties(HttpsURLConnectionImpl.java:25)
                                                                          at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getRequestProperties(TrackedHttpURLConnection.java:204)
                                                                          at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackPreConnect(TrackedHttpURLConnection.java:63)
                                                                          at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:354)
                                                                          at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.getInputStream(HttpsURLConnection$.java:261)
                                                                          at es.voghdev.pdfviewpager.library.remote.DownloadFileUrlConnectionImpl$1.run(DownloadFileUrlConnectionImpl.java:62)
                                                                          at java.lang.Thread.run(Thread.java:818)`

This happened when I upgraded the Gradle Build Tool to 3.0.1. RemotePDFViewPager works fine when downgrading the Gradle to 2.3.0

**Comment by voghDev** [comment]
Seems related to the HTTP download

just noticed that the DownloadFile collaborator inside `RemotePdfViewPager` can't be changed. I'll modify this to inject it via constructor, so it can be swapped by another implementation.

In the meanwhile, you can do your own `RemotePdfViewPager` by subclassing `PdfViewPager` directly, and manage your own download of the PDF file. 

Copy and paste [the code](https://github.com/voghDev/PdfViewPager/blob/master/library/src/main/java/es/voghdev/pdfviewpager/library/RemotePDFViewPager.java) and use another collaborator to download the file instead of `DownloadFileUrlConnectionImpl` 

Hope this helps

**Comment by MadAxon** [comment]
> Copy and paste the code and use another collaborator to download the file instead of DownloadFileUrlConnectionImpl
Another collaborator helped me and now PdfViewPager works! Thanks!
