### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by yanchenling** [voghDev/PdfViewPager#79]
java.lang.OutOfMemoryError: Failed to allocate a 230400012 byte allocation with 16406788 free bytes and 168MB until OOM
                                                                             at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                             at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                             at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
                                                                             at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
                                                                             at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
                                                                             at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.createBitmapAtIndex(SimpleBitmapPool.java:83)
                                                                             at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.getBitmap(SimpleBitmapPool.java:49)
                                                                             at es.voghdev.pdfviewpager.library.adapter.SimpleBitmapPool.get(SimpleBitmapPool.java:59)
                                                                             at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.instantiateItem(PDFPagerAdapter.java:60)

**Comment by voghDev** [comment]
This happened loading one page of your PDF document into a Bitmap. Either your PDF document is too heavy, or your device didn't have enough available memory in that moment. You can verify that you have enough space available before starting to render the PDF file
