### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Already closed

### ISSUE THREAD

**Issue by iad24** [voghDev/PdfViewPager#89]
Im using v1.0.3

```
Fatal Exception: java.lang.IllegalStateException: Already closed
       at android.graphics.pdf.PdfRenderer.throwIfClosed(PdfRenderer.java:254)
       at android.graphics.pdf.PdfRenderer.getPageCount(PdfRenderer.java:188)
       at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.getCount(BasePDFPagerAdapter.java:174)
       at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2171)
       at android.view.View.dispatchTouchEvent(View.java:10084)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2631)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2633)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2633)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2633)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2633)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2633)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2336)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2633)
       at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2474)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3191)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3271)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6015)
       at android.view.ViewRootImpl.die(ViewRootImpl.java:5992)
       at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:446)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:384)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4340)
       at android.app.ActivityThread.-wrap6(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6256)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
```

Full logs:
[crash1.txt](https://github.com/voghDev/PdfViewPager/files/2139799/crash1.txt)

**Comment by voghDev** [comment]
Hello,

what operation are you trying to perform when you got this error? what sequence of steps led you to it?

**Comment by iad24** [comment]
@voghDev I'm not sure. This crash log is from production which was done by my app user.
Is it difficult to trace from the logs?

**Comment by voghDev** [comment]
I'm afraid the user is trying to render a Pdf that exists inside a `Context` that has already been destroyed. This could happen if the user requests the file in an asynchronous process, such as an asynctask, and tries to render it in the `onResult` method. If the Context has already been destroyed, the PagerAdapter will receive an invalid Context, and therefore will crash. 

I close it after a few while without news and feel free to reopen it if you have further information

Thanks

**Comment by lamrak** [comment]
Folks, I have the same issue (or similar) if you open pdf file and app goes to background and if you try to go to app back - you will see this crash.

**Comment by gjerson2m** [comment]
Experimente el mismo error, y el problema es que estaba cerrado el PdfRenderer y el ParcelFileDescriptor en el onStop().

Aquí estaba el problema

`@Override
    public void onStop() {
        super.onStop();
        try {
            if (currentPage != null) {
                currentPage.close();
            }
            pdfRenderer.close();
            parcelFileDescriptor.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }`

Lo único que hice es cambiar **onStop()** a **onDestroy()**

y el problema se soluciono. espero te ayude.

**Comment by ironpython37** [comment]
https://stackdev.space/questions/how-do-i-create-a-dynamic-viewpager-in-android-that-adjusts-its-number-of-pages-based-on-the-results-of-an-asynctask I grasped the answer
