### ISSUE TITLE
How to use library lower than API 21 

### ISSUE THREAD

**Issue by golfyzzz** [voghDev/PdfViewPager#9]
Hello,
## code
if (Build.VERSION.SDK_INT >= 21) {
                adapter = new PDFPagerAdapter(this, file.getAbsolutePath(), pdfViewPager.getOffscreenPageLimit());
                pdfViewPager.setAdapter(adapter);
            }
            else {
                pdfViewPager = new PDFViewPager(context, file.getAbsolutePath());
                setContentView(pdfViewPager);

            }

## error
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.NoClassDefFoundError: android.graphics.pdf.PdfRenderer
                                                     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.init(BasePDFPagerAdapter.java:62)
                                                     at es.voghdev.pdfviewpager.library.adapter.BasePDFPagerAdapter.<init>(BasePDFPagerAdapter.java:56)
                                                     at es.voghdev.pdfviewpager.library.adapter.PDFPagerAdapter.<init>(PDFPagerAdapter.java:37)
                                                     at es.voghdev.pdfviewpager.library.PDFViewPager.initAdapter(PDFViewPager.java:62)
                                                     at es.voghdev.pdfviewpager.library.PDFViewPager.init(PDFViewPager.java:41)
                                                     at es.voghdev.pdfviewpager.library.PDFViewPager.<init>(PDFViewPager.java:31)
                                                     at com.example.golfyzzz.pdfviewer.SignatureActivity.initViewPDF(SignatureActivity.java:149)
                                                     at com.example.golfyzzz.pdfviewer.SignatureActivity.onActivityResult(SignatureActivity.java:483)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:5466)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3550)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3597)
                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:175)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
                                                     at android.os.Handler.dispatchMessage(Handler.java:107)
                                                     at android.os.Looper.loop(Looper.java:194)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5434)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by voghDev** [comment]
When your SDK version is below 21, you have to download the PDF file to your SD card, then call Android's native intent to display a PDF document.

You can download the file using DownloadFile abstract class and its implementation.

See the [Legacy sample](https://github.com/voghDev/PdfViewPager/blob/master/sample/src/main/java/es/voghdev/pdfviewpager/LegacyPDFActivity.java) included on samples project.

You can also check if the device can display PDF documents with a code similar to this one:

    public static boolean canDisplayPdf(Context context) {
        PackageManager packageManager = context.getPackageManager();
        Intent testIntent = new Intent(Intent.ACTION_VIEW);
        testIntent.setType(Constants.MIME_TYPE_PDF);
        if (packageManager.queryIntentActivities(testIntent, PackageManager.MATCH_DEFAULT_ONLY).size() > 0) {
            return true;
        } else {
            return false;
        }
    }

**Comment by voghDev** [comment]
I reopen this to let you know if you have any further comments.

**Comment by voghDev** [comment]
Closed it after a reasonable time :)

**Comment by ilakkiyaj** [comment]
how to solve this issue? need solution.

**Comment by voghDev** [comment]
@ilakkiyaj see my comment above
